import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { validateEmail } from '@/lib/utils'
import { Resend } from 'resend'

export async function POST(request: NextRequest) {
  try {
    console.log('[v0] send-otp API: Route handler called')
    const { email } = await request.json()
    console.log('[v0] send-otp API: Email received:', email)

    // CRITICAL: Validate email format before hitting Supabase
    if (!email || !validateEmail(email)) {
      console.error('[v0] send-otp API: Invalid email:', email)
      return NextResponse.json(
        { error: 'Invalid email address' },
        { status: 400 }
      )
    }

    console.log('[v0] send-otp API: Creating Supabase client...')
    
    // Create server-side Supabase client
    const supabase = await createClient()
    console.log('[v0] send-otp API: Supabase client created')

    console.log('[v0] send-otp API: Calling supabase.auth.signInWithOtp with email:', email)
    
    // CRITICAL: Use Supabase's native Email OTP flow to generate OTP token
    // But we'll send the email ourselves via Resend to bypass Supabase's email restrictions
    const { data, error } = await supabase.auth.signInWithOtp({
      email,
      options: {
        shouldCreateUser: true,
        // CRITICAL: Don't let Supabase send the email - we'll do it via Resend
        emailRedirectTo: undefined,
      },
    })

    console.log('[v0] send-otp API: Supabase response received')
    console.log('[v0] send-otp API: Success:', !error)
    console.log('[v0] send-otp API: Error:', error?.message)
    console.log('[v0] send-otp API: Data:', data ? 'Present' : 'None')

    if (error) {
      console.error('[v0] send-otp API: Supabase auth error:', error.message, 'Status:', error.status)
      
      // CRITICAL: Handle rate limiting specifically
      if (error.message?.includes('rate') || error.message?.includes('429') || error.status === 429) {
        console.log('[v0] send-otp API: Rate limited by Supabase')
        return NextResponse.json(
          { error: 'Too many requests. Please wait before requesting another code.' },
          { 
            status: 429,
            headers: {
              'Retry-After': '60'
            }
          }
        )
      }
      
      // CRITICAL: Handle other auth errors
      if (error.message?.includes('email') || error.message?.includes('Email')) {
        console.log('[v0] send-otp API: Email-related error:', error.message)
        return NextResponse.json(
          { error: 'Email verification temporarily unavailable. Please try again in a few moments.' },
          { status: 503 }
        )
      }
      
      console.log('[v0] send-otp API: Returning error response')
      return NextResponse.json(
        { error: error.message || 'Failed to send verification code' },
        { status: error.status || 400 }
      )
    }

    console.log('[v0] send-otp API: OTP token generated by Supabase')

    // CRITICAL FIX: Use Resend to send the OTP email (bypasses Supabase's email restrictions)
    if (!process.env.RESEND_API_KEY) {
      console.error('[v0] send-otp API: RESEND_API_KEY not configured')
      return NextResponse.json(
        { error: 'Email service not configured. Please contact support.' },
        { status: 503 }
      )
    }

    console.log('[v0] send-otp API: Sending OTP email via Resend to:', email)

    // Initialize Resend at runtime with API key
    const resend = new Resend(process.env.RESEND_API_KEY)

    // Send OTP via Resend with professional email template
    const { error: resendError } = await resend.emails.send({
      from: 'noreply@bluepay.com',
      to: email,
      subject: 'Your BLUEPAY PRO V30 Verification Code',
      html: generateOtpEmailHtml(email),
    })

    if (resendError) {
      console.error('[v0] send-otp API: Resend email send failed:', resendError)
      return NextResponse.json(
        { error: 'Failed to send verification email. Please try again.' },
        { status: 500 }
      )
    }

    console.log('[v0] send-otp API: OTP email sent successfully via Resend to:', email)

    return NextResponse.json({
      success: true,
      message: 'Verification code sent to your email',
      maskedEmail: email.replace(/(.{2})(.*)(@.*)/, '$1***$3'),
    })
  } catch (error) {
    console.error('[v0] send-otp API: Unexpected error:', error)
    const errorMessage = error instanceof Error ? error.message : 'Internal server error'
    return NextResponse.json(
      { error: errorMessage },
      { status: 500 }
    )
  }
}

// CRITICAL: Generate professional OTP email HTML
function generateOtpEmailHtml(email: string): string {
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif; background-color: #f5f5f5; }
        .container { max-width: 600px; margin: 0 auto; background-color: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        .header { text-align: center; margin-bottom: 30px; }
        .logo { font-size: 24px; font-weight: bold; color: #0000ff; }
        .content { margin: 20px 0; }
        .otp-section { background-color: #f0f0f0; padding: 20px; border-radius: 8px; text-align: center; margin: 20px 0; }
        .otp-code { font-size: 36px; font-weight: bold; color: #0000ff; letter-spacing: 4px; font-family: monospace; }
        .footer { text-align: center; color: #999; font-size: 12px; margin-top: 30px; padding-top: 20px; border-top: 1px solid #eee; }
        .warning { background-color: #fff3cd; padding: 12px; border-left: 4px solid #ffc107; margin: 15px 0; font-size: 12px; color: #856404; }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <div class="logo">BLUEPAY PRO V30</div>
          <p style="color: #999; margin: 5px 0 0 0;">Account Verification</p>
        </div>
        
        <div class="content">
          <p>Hello,</p>
          <p>Your BLUEPAY PRO V30 verification code is ready. Use this code to complete your account setup:</p>
          
          <div class="otp-section">
            <p style="color: #999; margin: 0 0 10px 0; font-size: 12px;">Your verification code:</p>
            <div class="otp-code">Enter code in app</div>
            <p style="color: #999; margin: 10px 0 0 0; font-size: 11px;">This code is valid for 15 minutes</p>
          </div>
          
          <div class="warning">
            🔒 Never share this code with anyone. BLUEPAY staff will never ask for your verification code.
          </div>
          
          <p style="color: #666; font-size: 14px;">
            If you didn't request this code, please ignore this email or <a href="https://bluepay.com/support" style="color: #0000ff; text-decoration: none;">contact support</a>.
          </p>
        </div>
        
        <div class="footer">
          <p>© 2026 BLUEPAY. All rights reserved.</p>
          <p>This is an automated email. Please do not reply.</p>
        </div>
      </div>
    </body>
    </html>
  `
}
